### PR TITLE
Migration to Play 2.6 and scala 2.12

### PR DESCRIPTION
**Pull request by ishishov**
Migration to Play 2.6 and scala 2.12
Fix for https://github.com/zalando-incubator/markscheider/issues/14

### CODE REVIEW

**Comment by musiKk** [comment]
I like that you not only did a simple update but made small improvements here and there.

**Comment by musiKk** [comment]
:+1:

**Comment by ishishov** [comment]
👍

**Comment by aakavalevich** [comment]
👍

**Pull request merged**
