### PR TITLE
Update sbt and dependencies

### PR DESCRIPTION
**Pull request by matterche**
Update sbt, sbt plugins, play framework and dependencies

### CODE REVIEW

**Comment by matterche** [comment]
@musiKk Would you mind also having a look at this one too? I currently don't have a second active maintainer.

**Comment by musiKk** [comment]
Sure. I'm not in the best position to actually test it right now. It builds, tests run and the changes look sensible.

**Comment by musiKk** [comment]
:+1:

**Comment by matterche** [comment]
👍

**Comment by matterche** [comment]
@musiKk Thanks a lot. I'll try to invest a bit more time in testing.

**Pull request merged**
