### PR TITLE
Migration to Play 2.7

### PR DESCRIPTION
**Pull request by mtrushin**
Migration to Play 2.7.0

### CODE REVIEW

**Comment by mtrushin** [comment]
👍

**Comment by ovolynets** [comment]
:+1:

**Comment by ovolynets** [comment]
Looks good to me but let's have @musiKk approval

**Comment by musiKk** [comment]
Looks also good to me. However, I'm not a maintainer of this project anymore. That would be @matterche or @alexkops .

**Review by matterche — APPROVED** [review]
Sorry, I completely missed this one. I will still need some time to prepare the release.

**Comment by matterche** [comment]
👍

**Comment by matterche** [comment]
@mtrushin @ovolynets the new version for Scala 2.12 is released. I hope you don't need a 2.11 version because there were problems I could not solve immediately.

**Pull request merged**
